require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'

namespace :db do
  task :load_config do
    require File.expand_path('app', __FILE__)
  end

  # added these lines to work
  task seed: :load_config do
  end
end
